### ISSUE TITLE
React Questions

### ISSUE THREAD

**Issue by nqthqn** [lumastories/hansel#1]
- [x] Should I use [react-templates](https://github.com/wix/react-templates) to decouple JSX from my `render()` method in my component class?
- [x] Should start learning [redux](https://github.com/reactjs/redux) right away or should I add it in later and refactor?
- [x] How do I use state to load component when network request finishes?
- [x] How do you use `async` and `await`?
- [x] How do I handle routes? (For example, showing login screen, authenticating, then showing data list)
- [x] How do I include bootstrap and other libs like `d3.js` in my SPA?
- [x] Should I use RxJS? What's thunks? 
- [x] Does `enzyme` not work with this version of React? I want to use `shallow()` to unit test bastardized Components.

thats it for now. gnight.

**Comment by nqthqn** [comment]
You could, but it's not necessary. Wait. You can always store the state in the root component. Redux as complexity so I would learn React first. If done right it should happen automatically. Check out this post -> https://medium.com/front-end-hacking/es7-async-await-with-react-native-35ca167cc326#.xqca2nict (For example, showing login screen, authenticating, then showing data list) Use react-router Use NPM to add in the dependencies If you are going to use rx, then you still need to use a state management framework like redux -> https://github.com/acdlite/redux-rx I want to use shallow() to unit test bastardized Components. Enzyme works with react versions .13x and above

**Comment by hath995** [comment]
Only thing I really have much to comment on is the RxJS question. I think this chart sums up the role that RxJS plays. http://reactivex.io/rxjs/manual/overview.html#observable. If you don't have a need for that bottom right corner of the the table then RxJS isn't going to provide you much utility over another promise library. 

A thunk is a piece of unprocessed work. I.e. a function. Raganwald explains it best. http://raganwald.com/2013/03/28/trampolines-in-javascript.html

**Comment by nqthqn** [comment]
https://ponyfoo.com/articles/understanding-javascript-async-await

**Comment by nqthqn** [comment]
http://nicolashery.com/integrating-d3js-visualizations-in-a-react-app/
